---
jenkins_plugins:
  - workflow-aggregator
  - pipeline-stage-view
  - workflow-multibranch
  - pipeline-model-definition
  - pipeline-groovy-lib
  - git
  - github
  - github-branch-source
  - credentials
  - credentials-binding
  - aws-credentials
  - aws-java-sdk
  - cloudbees-credentials
  - cloudbees-folder
  - ansiColor
  - timestamps
  - build-timeout
  - rebuild
  - ws-cleanup
  - artifact-manager-s3
