---
jenkins_plugins:
  - workflow-aggregator
  - pipeline-stage-view
  - workflow-multibranch
  - pipeline-model-definition
  - git
  - github
  - credentials
  - credentials-binding
  - aws-java-sdk
  - cloudbees-credentials
  - cloudbees-folder
  - ansicolor
  - timestamper
  - build-timeout
  - ws-cleanup
  - artifact-manager-s3
  - aws-credentials