---
- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: restart voting-app
  become: yes
  service:
    name: voting-app
    state: restarted
  when: ansible_facts['service_mgr'] == "systemd"
